# name: 'optura-light'
# url: https://optura.ai
# preferred_background: f0eee4

fish_color_normal 1a1616
fish_color_command 2a7d6a
fish_color_param 56524a
fish_color_keyword 420d41
fish_color_quote 8b6914
fish_color_redirection 2a7d6a
fish_color_end 8b6914
fish_color_comment 7a756a
fish_color_error a33b3b
fish_color_gray 7a756a
fish_color_selection --background=d9ecf7
fish_color_search_match --background=d9ecf7
fish_color_option 8b6914
fish_color_operator 2a7d6a
fish_color_escape 420d41
fish_color_autosuggestion 7a756a
fish_color_cancel a33b3b
fish_color_cwd 8b6914
fish_color_user 2a7d6a
fish_color_host 202e42
fish_color_host_remote 8b6914
fish_color_status a33b3b
fish_pager_color_progress 7a756a
fish_pager_color_prefix 2a7d6a
fish_pager_color_completion 1a1616
fish_pager_color_description 7a756a
